---
#run-go:
#  stage: build
#  script:
#    - sqlc generate
#    - go build .

deploy-proxmox-abed:
  tags:
    - ichi
  stage: deploy
  script:
    - pushd /srv/boop-server
    - find . -delete
    - popd
    - cp -r . /srv/boop-server
    - sudo /usr/bin/systemctl restart boop-server

deploy-proxmox-raed:
  tags:
    - ni
  stage: deploy
  script:
    - pushd /srv/boop-server
    - find . -delete
    - popd
    - cp -r . /srv/boop-server
    - sudo /usr/bin/systemctl restart boop-server

deploy-proxmox-elena:
  tags:
    - san
  stage: deploy
  script:
    - pushd /srv/boop-server
    - find . -delete
    - popd
    - cp -r . /srv/boop-server
    - sudo /usr/bin/systemctl restart boop-server
