---
#run-go:
#  stage: build
#  script:
#    - sqlc generate
#    - go build .

deploy-proxmox:
  tags:
    - boop
  stage: deploy
  script:
    - pushd /srv/boop-server
    - find . -delete
    - popd
    - cp -r . /srv/boop-server
    - sudo /usr/bin/systemctl restart boop-server
